version: '3'

services:
  main:
    image: hello-world
    volumes:
      - main-data:/var/lib/my-app-data

  backup:
    image: debian:latest
    environment:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
      BACKUPDEST: ${BACKUPDEST:?undefined target directory}
    volumes:
      - main-data:/data
      - ./scripts:/scripts
      # Binding directly to $MOUNTPOINT/$BACKUPDEST fails if root can't browse
      # up to that level due to restrictions on the remote filesystem.
      # Binding to $MOUNTPOINT has a better chance of working since the
      # directory must exist on the host.
      - ${MOUNTPOINT:?undefined mountpoint}:/mountpoint
    entrypoint: ["/scripts/entrypoint.sh"]
    depends_on:
      - main

volumes:
  main-data:
