version: '3'

services:
  main:
    # The image traefik/whoami is used here as a placeholder for the actual main service.
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.services.main.loadbalancer.server.port=${MAIN_SERVICE_PORT:-8080}
      - traefik.http.routers.main.tls=true
      - traefik.http.routers.main.entrypoints=websecure
      - traefik.http.routers.main.rule=Host("${HOST_HEADER_VALUE:-example.org}")

  # For additional examples, see:
  #   - https://traefik.io/blog/traefik-2-0-docker-101-fc2893944b9d/
  #   - https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/
  traefik:
    image: traefik:latest
    command:
      # Enable Traefik only for services that contain the label "traefik.enable=true".
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      # Redirect HTTP traffic to HTTPS.
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      # By default, Traefik generates a self-signed certificate.
      # To use certificate files from the host, enable the file provider below
      # and mount the relevant configuration + certificates.
      # - --providers.file.directory=/configuration/
      # - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - main
