version: '3'

services:
  main:
    image: hello-world

  cron:
    image: debian:latest
    environment:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
      SCHEDULE: ${SCHEDULE:-15 4 * * *}
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/scripts/entrypoint.sh"]
